---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-k8s-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-polling-deployment
  namespace: devops-k8s-ns
  labels:
    app: azdo-polling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdo-polling
  template:
    metadata:
      labels:
        app: azdo-polling
    spec:
      serviceAccountName: azdo-polling-sa
      containers:
      - name: azdo-polling-container
        image: YOUR_DOCKER_IMAGE_PATH_HERE #jtoledog/polling-ado-aks
        env:
        - name: ADO_PAT
          valueFrom:
            secretKeyRef:
              name: azdo-secret
              key: ADO_PAT
        - name: ADO_NAME
          valueFrom:
            secretKeyRef:
              name: azdo-secret
              key: ADO_NAME
        - name: ADO_MAX_SELF_HOSTED_AGENTS
          valueFrom:
            secretKeyRef:
              name: azdo-secret
              key: ADO_MAX_SELF_HOSTED_AGENTS
        - name: ADO_POOL
          valueFrom:
            secretKeyRef:
              name: azdo-secret
              key: ADO_POOL
