apiVersion: v1
kind: ServiceAccount
metadata:
  name: azdo-polling-sa
  namespace: devops-k8s-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-k8s-ns
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: devops-k8s-ns
subjects:
- kind: ServiceAccount
  name: azdo-polling-sa
  namespace: devops-k8s-ns
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io