#kubectl create secret generic azdo-secret --from-literal=pat=TU_PERSONAL_ACCESS_TOKEN
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-polling-deployment
  labels:
    app: azdo-polling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdo-polling
  template:
    metadata:
      labels:
        app: azdo-polling
    spec:
      containers:
      - name: azdo-polling-container
        image: YOUR_DOCKER_IMAGE_PATH_HERE
        env:
        - name: AZDO_PAT
          valueFrom:
            secretKeyRef:
              name: azdo-secret
              key: pat
